name: deploy-pipeline
on:
    workflow_dispatch:
      inputs:
        TF_ROOT:
          description: 'Carpeta del código a ejecutar el pipeline'
          required: true
env:
    TF_VAR_repo_url: ${{ github.repositoryUrl }}
    TF_VAR_repo_commit: ${{ github.sha }} 
jobs:
    #cancel-workflows:
    #    runs-on: ubuntu-latest
    #    steps:
    #        - name: Cancel Workflow Action
    #          uses: styfle/cancel-workflow-action@0.11.0
    deploy:
        defaults:
          run:
            working-directory: ${{ github.event.inputs.TF_ROOT }}
        runs-on: ubuntu-latest
        steps:          
            - uses: actions/checkout@v3
            - uses: hashicorp/setup-terraform@v2  
            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check
              continue-on-error: true            
            - name: Terraform Init
              id: init
              run: terraform init  
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}           
            - name: Terraform Apply
              id: apply
              run: terraform apply --var-file=../generic-files/variables.tfvars --auto-approve 
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
                AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 